DR/DR/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('dr.urls',namespace='dr')),
]

DR/dr/urls.py
#coding:utf-8
from django.conf.urls import url

from dr import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^goodlist/$',views.goodlist,name='goodlist'),
    url(r'^goodinfo/(\d+)$',views.goodinfo,name='goodinfo'),
    url(r'^goodsinfo/$',views.goodsinfo,name='goodsinfo'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^register/$',views.register,name='register'),
    url(r'^shopcar/$',views.shopcar,name='shopcar'),
    url(r'^test/$',views.test,name='test'),
    url(r'^addcart/$',views.addcart,name='addcart'),
    url(r'^rmcart/$',views.rmcart,name='rmcart'),
    url(r'^removecart/$',views.removecart,name='removecart'),
    url(r'^change/$',views.change,name='change'),
    url(r'^makeorder/$',views.makeorder,name='makeorder'),
    url(r'^appnotify/',views.appnotify,name='appnotify'),
    url(r'^returnview/$',views.returnview,name='returnview'),
    url(r'^pay/$',views.pay,name='pay')
]

DR/dr/models.py
from django.db import models

class User(models.Model):
    phone = models.CharField(max_length=11)
    pwd = models.CharField(max_length=255)
    token = models.CharField(max_length=255)

class Goods(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    num = models.IntegerField()
    user = models.ManyToManyField(User)

class Allimg(models.Model):

    name = models.CharField(max_length=100)
    adress = models.CharField(max_length=255)
    goods = models.ForeignKey(Goods,on_delete=None,null=True)

class Goodslist(models.Model):
    name = models.CharField(max_length=20)
    price = models.CharField(max_length=10)
    src = models.CharField(max_length=100)
    discript = models.CharField(max_length=100)
    sale = models.IntegerField(default=0)
    com = models.IntegerField(default=0)
    material1 = models.CharField(max_length=10)
    material2 = models.CharField(max_length=10)
    price1 = models.IntegerField(default=0)
    price2 = models.IntegerField(default=0)
    isselect = models.BooleanField(default=True)

class Goodsimg(models.Model):
    src = models.CharField(max_length=100)
    goods = models.ForeignKey(Goodslist)

class Cart(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(Goodslist)
    num = models.IntegerField()
    isselect = models.BooleanField(default=True)

class Order(models.Model):
    user = models.ForeignKey(User)
    status = models.IntegerField(default=0)
    createtime = models.DateTimeField(auto_now_add=True)
    orderid = models.CharField(max_length=256)

class OrderGoods(models.Model):

    order = models.ForeignKey(Order)
    goods = models.ForeignKey(Goodslist)

    number = models.IntegerField()

DR/templates/goodsinfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>戴瑞主页</title>
    <script src="{% static 'js/jquery-1.12.0.js' %}" ></script>
	<link rel="stylesheet" href="{% static 'css/style1.css' %}" >
	<link rel="stylesheet" href="{% static 'css/reset.css' %}" >
	<link rel="stylesheet" href="{% static 'css/goodsinfo.css' %}" >

	<script src="{% static 'js/index.js' %}" ></script>
	<script src="{% static 'js/goodinfo.js' %}" ></script>
	<script src="{% static 'js/banner.js' %}" ></script>

</head>
<body>
<!-- 头部 -->
	<div class="header">
		<div class="header_cen">
			<div class="header_cen_lf">
				<a href="#"><img src="{% static 'images/drlogo.png' %}" alt=""></a>
			</div>
			<div class="header_cen_rg">
				<div class="header_cen_rg_top">
					<ul>
						{% if name %}
                            <a href="#"><li >{{ name }}</li></a>
                            <a href="{% url 'dr:logout' %}"><li >logout</li></a>
                        {% else %}
                            <a href="{% url 'dr:login' %}"><li class="dl">登录</li></a>
                        {% endif %}
						<li class="join"><a href="#">加入DR族</a></li>
						<li class="num"> 400 01 13520</li>
						<li class="mobile">DR族APP
							<div>
								<img src="{% static 'images/app_ewm.jpg' %}" alt="">
								<p>信仰真爱的DR族都在扫码下载手机应用</p>
							</div>
						</li>
						<li class="lan"><a href="javascript:StranBody()" id="StranLink" title="以繁体中文瀏览">中文 (繁体)</a><script language="JavaScript" src="/static/js/big52gb.js" type="text/javascript"></script>
							<ul>
								<!-- <li><a href="#" class="tra">中文(繁体)</a></li> -->
								<li><a href="#">English</a></li>
							</ul>
						</li>
						<li class="city">所在城市店铺:</li>
							<div class="allCity">
								<!-- <span>岳阳</span> -->
							</div>
					</ul>
				</div>
				<div class="header_cen_rg_bot">
					<img src="{% static 'images/drz.png' %}" alt="">
					<div class="info">
						<select name="" id="">
							<option value="中国大陆" selected="selected">中国大陆</option>
							<option value="海外地区">海外地区</option>
							<option value="港澳台">港澳台</option>
							<option value="其他">其他</option>
						</select>
						<input type="text" placeholder="请输入身份证号验证真爱承诺">
						<input type="button" value="DR真爱查询">
						<span>Darry Ring严格规定男士凭身份证一生仅能定制一枚，象征男人一生真爱的最高承诺。输入身份证号码即可查询购买记录。</span>
						<i>身份证有误，请重新输入。</i>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- 头部 -->


	<!-- 导航栏 -->
	<div id="nav">
		<ul>
			<li class="dl_nav"><a href="#">DR</a>
				<div class="block_dl">
					<div class="dleft">
						<img class="d1" src="{% static '' %}" alt="">
						<a href="#">加入DR</a>

					</div>
					<div class="dright">
						<img class="d1" src="{% static '' %}" alt="">
						<p><a href="#"><span>立即选购</span><img src="{% static 'images/black_icon.png' %}" alt=""></a></p>
					</div>
				</div>
			</li>
			<li class="pro_nav"><a href="#">求婚钻戒</a>
				<div class="block">
					<div class="left">
						<div class="left_img">
							<img src="{% static 'images/20150129114316f8a2465758.jpg' %}" alt="">
						</div>
						<ul>
						<!-- 	<li>对戒</li>
							<li>男戒</li>
							<li>吊坠</li>
							<li>耳饰</li>
							<li>手链/手镯</li> -->
						</ul>
					</div>
					<div class="right">
						<div class="right_img">
							<img src="{% static 'images/20150129114316f8a2465758.jpg' %}" alt="">
						</div>
						<ul>
							<!-- <li>对戒</li>
							<li>男戒</li>
							<li>吊坠</li>
							<li>耳饰</li>
							<li>手链/手镯</li> -->
						</ul>
					</div>
				</div>
			</li>
			<li class="gift_nav"><a href="#">爱的礼物</a>
				<div class="block">
					<div class="left">
						<div class="left_img">
							<img src="{% static 'images/20150129114316f8a2465758.jpg' %}" alt="">
						</div>
						<ul></ul>
					</div>
					<div class="right">
						<div class="right_img">
							<img src="{% static 'images/20150129114316f8a2465758.jpg' %}" alt="">
						</div>
						<ul></ul>
					</div>
				</div>
			</li>

			<li class="dz_nav"><a href="#">钻戒定制</a></li>

			<li class="shop_nav"><a href="#">DR实体店</a>
				<div class="block_dl">
					<div class="dleft">
						<div class="hotCity">
							<h5>热门城市</h5>
							<div class="h-city">
								<a href="#">香港</a>
								<a href="#">香港</a>
								<a href="#">香港</a>
								<a href="#">香港</a>
								<a href="#">香港</a>
							</div>
						</div>

						<ul class="tab_class">
						<img class="line" src="{% static 'images/lright.jpg' %}" alt="">
							<li>
								<b class="active">华东区</b>
								<p style="opacity: 1;">
								</p>
							</li>
							<li>
								<b>华中区</b>
								<p style="opacity: 0;">
								</p>
							</li>
							<li>
								<b>华北区</b>
								<p style="opacity: 0;">
								</p>
							</li>
							<li>
								<b>华南区</b>
								<p style="opacity: 0;">
								</p>
							</li>
							<li>
								<b>西南区</b>
								<p style="opacity: 0;">
								</p>
							</li>
							<li>更多&gt;&gt;</li>
						</ul>
					</div>
					<div class="right">
						<div class="right_img">
							<img src="{% static 'images/20150129114316f8a2465758.jpg' %}" alt="">
						</div>
						<ul></ul>
					</div>
				</div>
			</li>
			<li class="brand_nav"><a href="#">DR品牌文化</a>
				<div class="block_dl">
					<div class="dleft">
						<img class="d6" src="{% static '' %}" alt="">
						<a class="a6" href="#"></a>

					</div>
					<div class="dright">
						<img class="d6" src="{% static '' %}" alt="">
						<a class="a6" href="#"></a>
					</div>
				</div>
			</li>
			<li class="com_nav"><a href="#">DR社区</a>
				<div class="block_dl">
					<div class="dleft">
						<img class="d7" src="{% static '' %}" alt="">
						<a class="a7" href="#"></a>

					</div>
					<div class="dright">
						<img class="d7" src="{% static '' %}" alt="">
						<a class="a7" href="#"></a>
					</div>
				</div>
			</li>
		</ul>
	</div>
	<!-- 导航栏 -->

	<!-- 轮播图 -->
	<div class="banner">
		<ul id="list">
				<!-- <li><img src="images/2016-1.jpg" alt=""></li>
				<li><img src="images/2016-2.jpg" alt=""></li>
				<li><img src="images/2016-3.jpg" alt=""></li>
				<li><img src="images/2016-4.jpg" alt=""></li> -->
		</ul>

		<ul id="list2">
				<!-- <li class='active'>1</li>
				<li>2</li>
				<li>3</li>
				<li>4</li> -->
		</ul>

			<div id="pre"><a href="#1"><img src="{% static 'images/leftbig.png' %}" alt=""></a></div>
			<div id="next"><a href="#1"><img src="{% static 'images/rightbig.png' %}" alt=""></a></div>
	</div>
	<!-- 轮播图 -->


	<!-- goodsinfo -->
	<div class="cort">
		<div class="tobuy cmain">
			<div class="spalid">
				<span>Skip Navigation Links Darry Ring &gt; 求婚钻戒 &gt; MY HEART 系列 &gt; MY HEART 系列 奢华款</span>
			</div>

			<div class="buy_cort">
				<div class="buycort_left fl">
					<ul class="bc_left">
						<li><img src="{% static 'images/2015093019140361614ead1d.jpg' %}" alt=""></li>
						<li><img src="{% static 'images/20150930191406bc384fe971.jpg' %}" alt=""></li>
						<li><img src="{% static 'images/2015093019140702298d7dbb.jpg' %}" alt=""></li>
						<li><img src="{% static 'images/20150930191409893f12c808.jpg' %}" alt=""></li>
					</ul>
				</div>
				<div class="buycort_center fl">
					<ul class="bc_center">
						<li>
							<!-- <img src="images/2015093019140361614ead1d.jpg" alt=""> -->
							<span></span>
						</li>
					</ul>
				</div>

				<div class="bigArea">
						<!-- <img class="bigImg" src="images/2015093019140361614ead1d.jpg" alt=""> -->
				</div>

				<div class="buycort_right fl">
					<div class="byright_top">
						<p>Sweety系列 满天星耳钉[G03002]</p>
						<p class="price"><span>￥2,599</span></p>
						<p class="xq">
							<i class="xq-sale">最近售出：3698</i>
							<i class="xq-mod">用户评论：2 收藏人气：180</i>
						</p>
					</div>
					<div class="byright_center">
						<p>
							<span>材质:</span>
							<i>白18K金</i>
							<i>白18K金</i>
						</p>
						<p>
							<span>数量:</span>
							<select name="" id="">
								<option value="size">1</option>
								<option value="size">2</option>
								<option value="size">3</option>
							</select>
						</p>
					</div>
					<div class="byright_bottom">
						<span class="join">加入购物车</span>
						<span class="payfor">立即购买</span>
					</div>

					<p class="d-link">DR爱的礼物，秋季回馈，点击进入&gt;</p>
				</div>
			</div>
		</div>
	</div>

	<!-- goodsinfo -->


	<div class="footer">
		<div class="dr_footer"></div>

		<ul class="dr_footer-icon w1000">
			<li><a href="#"><i class="icon1"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon2"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon3"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon4"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon5"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon6"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon7"></i><span>权威认证</span></a></li>
		</ul>

		<div class="dr_gray">
			<div class="w1000">
				<div class="dr-help-l">
					<a href="#" class="attenus">关注我们
						<div class="att">
							<span class="att_wb"></span>
							<span class="att_qz"></span>
							<span class="att_rr"></span>
							<span class="att_fb"></span>
							<span class="att_tw"></span>
							<img src="{% static 'images/app_ewm.jpg' %}" alt="">
						</div>
					</a>
					<a href="#">真爱查询</a>
					<a href="#">实体店免费预约</a>
					<a href="#">在线客服</a>
				</div>
				<div class="dr-help-r">
					<p>24小时全国免费服务热线</p>
					<p><img src="{% static 'images/tel.png' %}" alt=""></p>
				</div>
			</div>
		</div>

		<div class="dr_black">
			<div class="w1000">
				<ul>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
				</ul>
			</div>

			<div class="dr_statement">
                <p>Copyright ©  2006-2016 www.darryring.com 戴瑞珠宝 All Rights Reserved. 粤ICP备11012085号-2</p>
                <p>ICP经营许可证粤B2-20140279 | 中国互联网违法信息举报中心 | 中国公安网络110报警服务 | 本网站提供所售商品的正式发票 </p>
            </div>

            <div class="dr_language">
            	<p>中文（简体）/ 中文（繁体）/ English</p>
            </div>
		</div>
	</div>


	<!-- 右侧导航 -->
	<div class="floor">
		<div id="top">
		<img src="{% static 'images/zxkf.gif' %}" alt="">
			<a href="#">在线<br>客服</a>
		</div>
		<div class="car size">
			<a href="#" class="same icon_1"></a>
			<div class=""></div>
			<i>0</i>
		</div>
		<div class="card size">
			<a href="#" class="same icon_1"></a>
			<div class=""></div>
		</div>
		<div class="mysave size">
			<a href="#" class="same icon_1"></a>
			<div class=""></div>
			<i>0</i>
		</div>
		<div class="save size">
			<a href="#" class="same icon_1"></a>
			<div class=""></div>
		</div>
		<div class="mob size">
			<a href="#" class="same icon_1"></a>
			<div class=""></div>
		</div>
		<div class="share size">
			<a href="#" class="same icon_1"></a>
			<div class=""></div>
		</div>
		<div class="back_top size">
			<a href="#" class="same icon_1"></a>
			<div class=""></div>
		</div>
		<div class="cbox">

		</div>
	</div>
	<!-- 右侧导航 -->
</body>
<script>

</script>
</html>

<!-- 
需要实现的功能：轮播图（JSON数据），放大镜，购物车，登录，注册，楼梯效果...
PC端的项目一般会写在工作简历上 

静态页面/动态页面
数据存储在数据库中 《-》 后台 《-》 前端(客户端)
ajax:接口（url）
做页面一般有两个事：调用接口 -》显示数据在页面上

c/s模式 客户端服务器模式
b/s模式 Brower/Server
后台语言：Java/.net/PHP
-->

DR/templates/login.html

{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>戴瑞主页</title>
	<link rel="stylesheet" href="{% static 'css/style1.css' %}" >
	<link rel="stylesheet" href="{% static 'css/reset.css' %}" >
	<link rel="stylesheet" href="{% static 'css/login.css' %}" >
    <script src="{% static 'js/jquery-1.12.0.js' %}" ></script>
	<script src="{% static 'js/index.js' %}" ></script>
{#	<script src="{% static 'js/base1.js' %}"></script>#}
	<script src="{% static 'js/login.js' %}" ></script>
	<script src="{% static 'js/banner.js' %}" ></script>
	<script src="{% static 'js/jquery.cookie.js' %}" ></script>

</head>
<body>
<!-- 头部 -->
	<div class="header">
		<div class="header_cen">
			<div class="header_cen_lf">
				<a href="#"><img src="{% static 'images/logo.png' %}" alt=""></a>
			</div>
			<div class="header_cen_rg">
				<div class="header_cen_rg_top">
					<ul>
						<li class="dl">登录</li>
						<li class="join"><a href="#">加入DR族</a></li>
						<li class="num"> 400 01 13520</li>
						<li class="help">更多帮助&gt;</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- 头部 -->


	<!-- 轮播图 -->
	<div class="banner">
		<ul id="list"></ul>
		<ul id="list2"></ul>

			<div id="pre"><a href="ideBar#1"><img src="{% static 'images/leftbig.png' %}" alt=""></a></div>
			<div id="next"><a href="#1"><img src="{% static 'images/rightbig.png' %}" alt=""></a></div>

	</div>

	<!-- 登录界面 -->
	<div class="login">
		<h3>DR族-登录</h3>
		<form action="{% url 'dr:login' %}" id="loginform" method="post">
        {% csrf_token %}
            <div class="check">
                <div class="info">1111</div>
                <input class="user" name="name" id="" type="text" placeholder="请输入您的邮箱/手机号码">
                <input class="pwd" name="pwd" id="" type="password" placeholder="请输入密码">
                <p>
                    <input type="checkbox" id="isRemeber"><label for="isRemeber">记住密码</label>
                    <a href="#" class="forget">忘记密码</a>
                </p>
                <div class="btn">
{#    				<a class="loginbtn">登录</a>#}
                    <input  type="submit" value="登录">
                    <a class="joindr" href="{% url 'dr:register' %}">加入DR族</a>

                </div>
            </div>
        </form>

			<div class="other_login">
				<h4>第三方账户登录</h4>
				<a href="#" class="qq"></a>
				<a href="#" class="wx"></a>
				<a href="#" class="wb"></a>
				<a href="#" class="zfb"></a>
			</div>
	</div>
	<!-- 登录界面 -->

	<!-- 轮播图 -->


	<!-- 底部 -->
	<div class="footer">
		<div class="dr_footer"></div>

		<ul class="dr_footer-icon w1000">
			<li><a href="#"><i class="icon1"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon2"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon3"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon4"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon5"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon6"></i><span>权威认证</span></a></li>
			<li><a href="#"><i class="icon7"></i><span>权威认证</span></a></li>
		</ul>

		<div class="dr_gray">
			<div class="w1000">
				<div class="dr-help-l">
					<a href="#" class="attenus">关注我们
						<div class="att">
							<span class="att_wb"></span>
							<span class="att_qz"></span>
							<span class="att_rr"></span>
							<span class="att_fb"></span>
							<span class="att_tw"></span>
							<img src="{% static 'images/app_ewm.jpg' %}" alt="">
						</div>
					</a>
					<a href="#">真爱查询</a>
					<a href="#">实体店免费预约</a>
					<a href="#">在线客服</a>
				</div>
				<div class="dr-help-r">
					<p>24小时全国免费服务热线</p>
					<p><img src="{% static 'images/tel.png' %}" alt=""></p>
				</div>
			</div>
		</div>

		<div class="dr_black">
			<div class="w1000">
				<ul>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
					<li>
						<h4>关于我们</h4>
						<a href="#">权威认证</a>
						<a href="#">合作专区</a>
						<a href="#">加入我们</a>
					</li>
				</ul>
			</div>

			<div class="dr_statement">
                <p>Copyright ©  2006-2016 www.darryring.com 戴瑞珠宝 All Rights Reserved. 粤ICP备11012085号-2</p>
                <p>ICP经营许可证粤B2-20140279 | 中国互联网违法信息举报中心 | 中国公安网络110报警服务 | 本网站提供所售商品的正式发票 </p>
            </div>

            <div class="dr_language">
            	<p>中文（简体）/ 中文（繁体）/ English</p>
            </div>
		</div>
	</div>
	<!-- 底部 -->


	<!-- 右侧导航 -->
	<div class="floor">
		<div id="top">
		<img src="{% static 'images/zxkf.gif' %}" alt="">
			<a href="#">在线<br>客服</a>
		</div>
		<div class="car size">
			<a href="#" class="same icon_1"></a>
			<div class="">购物车</div>
			<i>0</i>
		</div>
		<div class="card size">
			<a href="#" class="same icon_1"></a>
			<div class="">我的订单</div>
		</div>
		<div class="mysave size">
			<a href="#" class="same icon_1"></a>
			<div class="">我的收藏</div>
			<i>0</i>
		</div>
		<div class="save size">
			<a href="#" class="same icon_1"></a>
			<div class="">收藏网站</div>
		</div>
		<div class="mob size">
			<a href="#" class="same icon_1"></a>
			<div class=""></div>
		</div>
		<div class="share size">
			<a href="#" class="same icon_1"></a>
			<div class=""></div>
		</div>
		<div class="back_top size">
			<a href="#" class="same icon_1"></a>
			<div class="">返回顶部</div>
		</div>
		<div class="cbox"></div>
	</div>
	<!-- 右侧导航 -->



<script>

</script>
</body>

<script>

</script>
</html>

DR/templates/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
{#    <script src="{% static 'js/jquery-1.12.0.js' %}"></script>#}
    <style>
    html, body {
      position: relative;
      height: 100%;
    }
    body {
      background: #eee;
      font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
      font-size: 14px;
      color:#000;
      margin: 0;
      padding: 0;
    }
    .swiper-container {
      width: 100%;
      height: 100%;
      margin-left: auto;
      margin-right: auto;
    }
    .swiper-slide {
      text-align: center;
      font-size: 18px;
      background: #fff;

      /* Center slide text vertically */
      display: -webkit-box;
      display: -ms-flexbox;
      display: -webkit-flex;
      display: flex;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      -webkit-justify-content: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      align-items: center;
    }
  </style>
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/swiper.js' %}"></script>

</head>
<body>
 <div class="swiper-container">
    <div class="swiper-wrapper">
            <div class="swiper-slide">111</div>
            <div class="swiper-slide">22</div>
            <div class="swiper-slide">33</div>
            <div class="swiper-slide"><img src="{% static 'images/2016-4.jpg' %}" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'images/2016-5.jpg' %}" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'images/2016-1.jpg' %}" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'images/2016-2.jpg' %}" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'images/2016-3.jpg' %}" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'images/2016-4.jpg' %}" alt=""></div>
            <div class="swiper-slide"><img src="{% static 'images/2016-5.jpg' %}" alt=""></div>
    </div>
     </div>
    <script>
    $(function () {
       var swiper = new Swiper('.swiper-container', {
      effect: 'coverflow',
      grabCursor: true,
      centeredSlides: true,
      slidesPerView: 'auto',
      coverflowEffect: {
        rotate: 50,
        stretch: 0,
        depth: 100,
        modifier: 1,
        slideShadows : true,
      },
      pagination: {
        el: '.swiper-pagination',
      },
    });
    })
  </script>
</body>

</html>